spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:patches}?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:${MYSQL_USER:patches}}
    password: ${DB_PASSWORD:${MYSQL_PASSWORD:patches}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: classpath:db/migration/mysql
