global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "patch-app-prod"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app:8080"]

  - job_name: "patch-app-blue"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app-blue:8080"]

  - job_name: "patch-app-green"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app-green:8080"]
